file:
  image-dir: app/static/images

spring:

  session:
    store-type: redis
    timeout: 1800s # 세션 만료시간 (30분)

  mail:
    host: smtp.naver.com
    port: 465
    username: "woniwory"
    password: "Woodpecker1324@"
    protocol: smtps
    from: "woniwory@naver.com"  # 발신자 이메일 추가
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true


  application:
    name: checkmate_backend





  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/capstone?authSource=admin

    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

app:
  reset-password:
    url: ${RESET_PASSWORD_URL:http://localhost:3000/reset-password?token=}

jwt:
  secret: "fhuiahfhaf98ahf89dshf8ahs9f8df89ahf89dshafffdfaf8as9fh89ashf98dashf9as8hfa89fhas89fhaf98dashfsa89fhdsa89fahf8d9sahfsa9f8hf8"
